[CONFIG]
; NTROBOT SETTINGS - VARIABILI REPLACE
; VERSIONE WINDOWS E LINUX
; ------------------------------------------------------------
TYPE=NTJOBS.CONFIG.1
EXPAND=True
EXIT=True
CYCLE.WAIT=15
SESSION=1

; SYSROOT - WINDOWS LINUX
SYSROOT=K:\ntjobsai2
;SYSROOT=/home/ntjobsai2

; CONFIG OBBLIGATORI
ARCHIVE=$SYSROOT\Archive
INBOX=$SYSROOT\Inbox
APPS=$SYSROOT\Apps
LOG=$SYSROOT\Log
ADMIN.EMAIL=ntgcorp@gmail.com

; CONFIG FACOLTATIVI
TEMP=$SYSROOT\Temp
USERS=$SYSROOT\Users

; PYTHON
PYTHON=$SYSROOT\Tools\pyn.cmd
;PYTHON=python3

; METODO INVIO MAIL PREVISTO
; 1=SMTP
;MAIL.ENGINE=SMTP
;MAIL.PATH=$APPS\ntj_sendmail\ntj_sendmail_smtp.sh

; 2=OLK 
MAIL.ENGINE=OLK
MAIL.PATH=$SYSROOT\Tools\olksendmail0\olksendmail.cmd
;MAIL.PATH=K:\Apps\ntj_sendmail\

