[CONFIG]
; NTROBOT SETTINGS - VARIABILI REPLACE
; ------------------------------------------------------------
TYPE=NTJOBS.CONFIG.1
EXPAND=True
EXIT=True
CYCLE.WAIT=15
SESSION=1

; CONFIG OBBLIGATORI
SYSROOT=K:\ntjobsai2
ARCHIVE=$SYSROOT\Archive
INBOX=$SYSROOT\Inbox
LOG=$SYSROOT\Log
ADMIN.EMAIL=ntgcorp@gmail.com

; CONFIG FACOLTATIVI
TEMP=$SYSROOT\Temp
NTROBOT=K:\ntRobot
PYTHON=$SYSROOT\pyn.cmd
USERS=$SYSROOT\Users

; METODO INVIO MAIL PREVISTO
; 1=SMTP
; 2=OLK 
MAIL.ENGINE=OLK
MAIL.PATH=Tools\olksendmail\olksendmail.cmd