ECHO Start ntJobsWindows
REM Versione 20250208
SET PY_TYPE=X64

@REM DIFFERENTE PER VARI COMPUTER 
@REM DEFAULT NTGDSNAS
SET PY_EXEC=X:\_NTGCORP\PythonX64\App\Python
@REM MACH0
IF EXIST K:\MACH0_PROD.TXT SET PY_EXEC=K:\TOOLS\PythonX64\App\Python
@REM CACHE LOCALE
IF EXIST D:\APPLIC\PYTHON\*.* SET PY_EXEC=D:\Applic\PythonX64\App\Python
IF EXIST C:\APPLIC\PYTHON\*.* SET PY_EXEC=C:\Applic\PythonX64\App\Python

:START
CALL pyn.cmd %1 %2 %3 %4 %5 %6 %7 %8 %9
